#!/usr/bin/env bash

title=$(playerctl metadata title)
artist=$(playerctl metadata artist)

if [[ -n "$title$artist" ]]
then
    echo "$(playerctl metadata title) - $(playerctl metadata artist)"
else
    echo ""
fi
