#!/usr/bin/env bash

set -eu

backup_file () {
  FILE=$1
  BACKUPDIR="$HOME/.old-dotfiles"
  PARENT=$2
  if [ ! -d "$BACKUPDIR" ]
  then
    mkdir -p "$BACKUPDIR"
  fi
  if [ ! -z "$PARENT" ]
  then
    mkdir -p "$BACKUPDIR/$PARENT"
  fi
  mv "$HOME/.$FILE" "$BACKUPDIR/${FILE#.}"
}

make_oh_my_zsh () {
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
}

make_syms () {
  FILES=$1
  PARENT=${2-""}
  WD=$(pwd)

  for f in $FILES/*
  do
    f_base="$PARENT$(basename "$f")"
    if [ -e "$HOME/.$f_base" ]
    then
      backup_file "$f_base" "$PARENT"
    fi

    if [ ! -z "$PARENT" ] && [ ! -d "$HOME/.$PARENT" ]
    then
      mkdir -p "$HOME/.$PARENT"
    fi

    ln -sf "$WD/$f" "$HOME/.$f_base"
  done
}

make_nested_syms () {
  PARENT=$1
  for p in $PARENT/*
  do
    make_syms $p "$(basename $p)/"
  done
}

make_base16 () {
  mkdir -p ~/.config/base16-shell
  git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell
  base16_tomorrow-night
}

make_tmux () {
  mkdir -p ~/.tmux/plugins
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  ~/.tmux/plugins/tpm/bin/install_plugins
}

make_vim () {
  mkdir -p ~/.vim/{autoload,backup,swap,undo}
  ln -s ~/.vim ~/.config/nvim
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  vim +PlugInstall +qall
  vim +UpdateRemotePlugins +qall
}

make_oh_my_zsh
make_syms files
make_nested_syms nested
make_base16
make_vim
make_tmux
