call plug#begin()

" All the plugins
" TODO Replace syntastic with neomake
Plug 'scrooloose/syntastic'
" Split into vim and nvim compatible functions
if has('nvim')
    function! DoRemote(arg)
      UpdateRemotePlugins
    endfunction
    Plug 'Shougo/deoplete.nvim', { 'do': function('DoRemote') }
else
    Plug 'Shougo/neocomplete.vim'
endif

" Other plugins
Plug 'tpope/vim-surround'
Plug 'tpope/vim-vinegar'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-abolish'
Plug 'Townk/vim-autoclose'
Plug 'airblade/vim-gitgutter'
"Plug 'zhaocai/GoldenView.Vim'
Plug 'bling/vim-airline'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'bkad/CamelCaseMotion'
Plug 'sjl/gundo.vim'

Plug 'moll/vim-bbye'
Plug 'majutsushi/tagbar'
Plug 'jpalardy/vim-slime'

Plug 'dyng/ctrlsf.vim'

" Language plugins
" Plug 'neovimhaskell/haskell-vim'
Plug 'bgapinski/vim2hs' "Personal fork
" Plin 'eagletmt/ghcmod-vim'
Plug 'eagletmt/neco-ghc'
Plug 'Twinside/vim-hoogle'
Plug 'idris-hackers/idris-vim'
Plug 'tmux-plugins/vim-tmux'
Plug 'nvie/vim-flake8'
Plug 'derekwyatt/vim-scala'
Plug 'dag/vim-fish'

"Instantly Better Plugins
Plug 'shinokada/listtrans.vim'
Plug 'atweiden/vim-vmath'
Plug 'jondkinney/dragvisuals.vim'

" Theme
Plug 'w0ng/vim-hybrid'

call plug#end()

filetype plugin indent on

syntax enable
filetype plugin on

" Basic settings
set autoindent
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set smarttab
set backspace=indent,eol,start
set number
set relativenumber
set ruler
set scrolloff=5
set showmode
set showcmd

set autoread

" Vim specifc settings
if !has('nvim')
  set encoding=utf-8
  set ttyfast
endif

set ffs=unix

set laststatus=2

set wildmenu
set wildmode=list:longest,full
set wildignore+=*.o,*.hi,*.aux,*.pyc,*.class

" Show bad whitespace
set list
if &listchars ==# 'eol:$'
  exec "set listchars=tab:\uBB\uBB,trail:\uB7,extends:>,precedes:<,nbsp:~"
endif

set cmdheight=1

set shell=zsh

set shortmess=atI

set hlsearch
set incsearch
set ignorecase
set smartcase
set showmatch

set noerrorbells
set vb t_vb=

set clipboard+=unnamedplus

set updatecount=0
set lbr
set tw=500
set wrap

set backupdir=~/.vim/backup//
set directory=~/.vim/swap//
set undodir=~/.vim/undo//
set undofile

set sessionoptions=blank,buffers,curdir,folds,globals,help,localoptions,options,resize,tabpages,winsize,winpos
cmap w!! %!sudo tee > /dev/null %

let $PATH = $PATH . ':' . expand("~/.vimscripts")

set mouse=a

set csto=1
set cst
set csverb
nnoremap <silent> <C-\> :cs find c <C-R>=expand("<cword>")<CR><CR>

set completeopt+=longest

set viminfo^=%
set tm=2000

" Terminal color
if &term =~ '256color'
  set t_ut=
endif

set t_Co=256
set background=dark
colorscheme hybrid

" Color long lines
highlight ColorColumn ctermbg=magenta
call matchadd('ColorColumn', '\%79v', 100)

hi Normal ctermbg = none
hi Search ctermfg=white ctermbg=173 cterm=none guifg=#ffffff guibg=#e5786d gui=none
hi! link Visual Search

" Key rebindings
let mapleader = "\<Space>"

nmap <Leader>ln :lnext<CR>
nmap <Leader>lp :lprev<CR>

vnoremap <Leader>y "+y
nnoremap <Leader>y "+y
vnoremap <Leader>d "+d
nnoremap <Leader>d "+d
vnoremap <Leader>p "+p
nnoremap <Leader>p "+p

nnoremap <Leader>tt :TagbarToggle<CR>
nnoremap <Leader>u :GundoToggle<CR>

nnoremap ; :
nnoremap j gj
nnoremap k gk

noremap <c-h> <c-w>h
noremap <c-k> <c-w>k
noremap <c-j> <c-w>j
noremap <c-l> <c-w>l

nmap <silent> <leader><cr> :noh\|hi Cursor guibg=red<cr>

" Ex mode is never used
map Q gq

map <S-W> <Plug>CamelCaseMotion_w
map <S-B> <Plug>CamelCaseMotion_b
map <S-E> <Plug>CamelCaseMotion_e

" Open window splits in various places
nmap <leader>wh :leftabove  vnew<CR>
nmap <leader>wl :rightbelow vnew<CR>
nmap <leader>wk :leftabove  new<CR>
nmap <leader>wj :rightbelow new<CR>

nmap <leader>b <Plug>CtrlSFPrompt<CR>
vmap <leader>b <Plug>CtrlSFVwordPath<CR>

" Source vimrc after saving it
augroup sourcing
  autocmd!
  if has('nvim')
    autocmd BufWritePost init.vim source $MYVIMRC
  else
    autocmd BufWritePost .vimrc source $MYVIMRC
  endif
augroup END

" Returns to last edit position when opening files.
augroup last_edit
  autocmd!
  autocmd BufReadPost *
       \ if line("'\"") > 0 && line("'\"") <= line("$") |
       \   exe "normal! g`\"" |
       \ endif
augroup END

" Delete trailing white space on save
func! DeleteTrailingWS()
  exe "normal mz"
  %s/\s\+$//ge
  exe "normal `z"
endfunc

" Automatically trim trailing whitespace in files.
augroup whitespace
  autocmd!
  autocmd BufWrite *.py,*.hs,*.scala,*.c :call DeleteTrailingWS()
augroup END

" Tmux-slime configuration
let g:slime_no_mappings = 1
let g:slime_target = "tmux"
let g:slime_paste_file = tempname()
let g:slime_python_ipython = 1
xmap <leader>s <Plug>SlimeRegionSend
nmap <leader>s <Plug>SlimeMotionSend
nmap <leader>ss <Plug>SlimeLineSend

" Various plugin initialization
if has('nvim')
  let g:deoplete#enable_at_startup = 1
else
  let g:neocomplete#enable_at_startup = 1
endif

let g:airline#extensions#tabline#enabled = 1
let g:ctrlp_map = '<Leader>e'

" Syntastic Config
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
hi! link SignColumn LineNr
hi! link SyntasticErrorSign ErrorMsg
hi! link SyntasticWarningSign WarningMsg
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_enable_highlighting = 1
let g:syntastic_enable_signs = 1
