#!/bin/bash

#compton --config ~/.compton.conf -b

xsetroot -cursor_name left_ptr

unclutter -grab &

xflux -z 11217
#/usr/bin/xscreensaver -no-splash &
#xss-lock -- xscreensaver-command -lock &

#touchegg &

feh --bg-scale ~/.wallpaper

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

setxkbmap -model pc105 -layout us,us -variant dvorak, -option grp:alt_shift_toggle -option ctrl:nocaps
xcape -e "Control_L=Escape"

#xrdb -merge ~/.Xresources

exec xmonad
