# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

autoload -U colors && colors

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="gentoo"

BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

fancy-ctrl-z () {
    if [[ $#BUFFER -eq 0 ]]; then
        fg
        zle redisplay
    else
        zle push-input
        zle clear-screen
    fi
}

zle -N fancy-ctrl-z

bindkey '^Z' fancy-ctrl-z
bindkey -v

fignore=(.o .hi .aux .pyc .class .ibc)

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias pacman="sudo pacman"
alias tmux="tmux -2"
alias pip="pip3"
alias vim="nvim"
alias vmi="nvim"
alias diff="colordiff"
alias sl="ls"
alias gti="git"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

NORMAL_INDICATOR="%{$fg_bold[red]%}[% N]% %{$reset_color%}"
INSERT_INDICATOR="%{$fg_bold[blue]%}[% I]% %{$reset_color%}"
OPP_INDICATOR="%{$fg_bold[yellow]%}[% O]% %{$reset_color%}"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(zsh-nvm gitfast tmux-custom colored-man vi-mode-custom opp opp-surround pip systemd)

ZSH_TMUX_AUTOSTART=false
ZSH_TMUX_AUTOQUIT=false

source $ZSH/oh-my-zsh.sh
export EDITOR=vim

export LESSOPEN="| $(which src-hilite-lesspipe.sh) %s"
export LESS=" -R "

# Customize to your needs...
export PATH=/home/brian/.cabal/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/brian/.scripts:$PATH

export WECHALLUSER="xechas"
export WECHALLTOKEN="D5B30-17222-EDA30-4E1C4-BFF39-587BC"

export ANDROID_HOME="/opt/android-sdk"

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
# source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
